add plurals to .POT
marcglasberg/i18n_extension pull request #78
Opened 2021-03-30 14:32 UTC by iuriegutu95

Adding plural suport for .POT export. The compiler was already working. I added a structure to report the request from plural in code to the extracting function.

2021-04-13 14:08 UTC, iuriegutu95 commented
Guys, this has been updated to fix importing of POT as well. @marcglasberg Can you merge this?

2021-04-13 14:55 UTC, marcglasberg commented
@bauerj Hello Johann, could you please approve, or not, this PR?

2021-04-13 15:24 UTC, bauerj requested changes
Thanks, this is awesome!

I do have a few things I would advise you to change though. Apart from those, this looks like excellent work!

2021-04-13 15:24 UTC, bauerj commented on lib/i18n_getstrings.dart
> +class DecodedSintax {
What does this mean? Did you mean Syntax?

2021-04-13 15:24 UTC, bauerj commented on lib/i18n_getstrings.dart
> +    final DecodedSintax sintax =
There is too much duplicated code now. Please factor this and the same code above out into a new method, e.g. `_handleI18nSyntax`.

2021-04-13 15:24 UTC, bauerj commented on lib/i18n_getstrings.dart
> +  final List<I18nRequiredModifiers> modifiers;
This looks a bit complicated for what you are trying to achieve. Wouldn't it be better to just add a `bool isPlural` to the class?

2021-04-14 11:40 UTC, iuriegutu95 commented
@bauerj I've added the changes. For the 3rd point - I wouldn't agree that it's too complex, it's ready for future usage like gender addition, etc. I would leave it like it is.

2021-04-14 11:41 UTC, iuriegutu95 commented
@bauerj following my comment, leave me a feedback if you think something else needs addressing, otherwise please merge it.

2021-04-14 11:43 UTC, bauerj approved these changes
![ship_it](https://user-images.githubusercontent.com/598790/114704857-5cbb5b80-9d27-11eb-8d33-b53f3ea9eccb.gif)

2021-04-14 11:45 UTC, bauerj commented
Thanks for your further improvements. IMO this is ready to merge now @marcglasberg.

2021-04-14 15:01 UTC, merged